### ISSUE TITLE
Consider merging with BrowserMediaKeys?

### ISSUE THREAD

**Issue by carlin-q-scott** [uFFFD/fx-mediakey#1]
[I also created a Firefox add-on](https://github.com/carlin-q-scott/browser-media-keys) around the same time for the same purpose but have been maintaining it and expanded the global support to Linux, along with many websites.

Your WinApi code looks like it would avoid some of the annoyances experienced by my users with keyboard apps interfering with hotkeys. We aren't using compatible licenses though (MPL v. GPL) so I cannot just copy your code.

**Comment by uFFFD** [comment]
sorry for the late reply
mk-win.js is now licensed under the MIT license
hope it helps

**Comment by carlin-q-scott** [comment]
Thanks, that does help. The MIT license seems to be compatible with the MPL.

**Comment by uFFFD** [comment]
no problem
